// Invite-only auth: env var ACCESS_KEYS holds comma-separated `name:key`
// pairs (keys generated by `npm run genkey <name>`). No user database.
//
// Security properties:
// - Keys are compared as SHA-256 digests with crypto.timingSafeEqual, and
//   every configured key is checked on every attempt (no early exit), so
//   timing reveals nothing about which key — or how much of a key — matched.
// - Malformed ACCESS_KEYS entries fail loudly at first use (boot, in effect),
//   never silently. Error messages name the entry position, never key material.
// - Unknown callers get an identical 401 whether the key is absent, malformed,
//   or merely wrong.

import { createHash, timingSafeEqual } from "node:crypto";

export const KEY_PATTERN = /^troll_[a-z2-7]{26}$/;
const NAME_PATTERN = /^[a-zA-Z0-9_-]{1,32}$/;

interface AccountEntry {
  name: string;
  keyHash: Buffer;
}

function sha256(input: string): Buffer {
  return createHash("sha256").update(input, "utf8").digest();
}

export function parseAccessKeys(raw: string | undefined): AccountEntry[] {
  if (!raw || raw.trim() === "") {
    throw new Error("ACCESS_KEYS is not set — refusing to serve an unauthenticated MCP endpoint");
  }
  const entries: AccountEntry[] = [];
  const seen = new Set<string>();
  const pairs = raw.split(",").map((p) => p.trim());
  pairs.forEach((pair, i) => {
    if (pair === "") {
      throw new Error(`ACCESS_KEYS entry ${i + 1} is empty (stray comma?)`);
    }
    const sep = pair.indexOf(":");
    if (sep === -1) {
      throw new Error(`ACCESS_KEYS entry ${i + 1} has no "name:key" separator`);
    }
    const name = pair.slice(0, sep).trim();
    const key = pair.slice(sep + 1).trim();
    if (!NAME_PATTERN.test(name)) {
      throw new Error(
        `ACCESS_KEYS entry ${i + 1} has an invalid account name (letters/digits/_/-, max 32 chars)`,
      );
    }
    if (!KEY_PATTERN.test(key)) {
      throw new Error(
        `ACCESS_KEYS entry ${i + 1} ("${name}") has a malformed key — expected troll_ + 26 base32 chars (run: npm run genkey ${name})`,
      );
    }
    if (seen.has(name)) {
      throw new Error(`ACCESS_KEYS has duplicate account name "${name}"`);
    }
    seen.add(name);
    entries.push({ name, keyHash: sha256(key) });
  });
  return entries;
}

let cachedEntries: AccountEntry[] | null = null;

function getEntries(): AccountEntry[] {
  if (cachedEntries === null) {
    cachedEntries = parseAccessKeys(process.env.ACCESS_KEYS);
  }
  return cachedEntries;
}

/** Test hook: force re-parse of ACCESS_KEYS on next verify. */
export function resetAccessKeysCache(): void {
  cachedEntries = null;
}

/**
 * Verify a candidate key. Returns the account name on match, null otherwise.
 * Constant-time with respect to which account (if any) matched.
 */
export function verifyKey(candidate: string | null | undefined): string | null {
  const entries = getEntries();
  const candidateHash = sha256(typeof candidate === "string" ? candidate : "");
  let matched: string | null = null;
  for (const entry of entries) {
    if (timingSafeEqual(candidateHash, entry.keyHash)) {
      matched = entry.name;
    }
  }
  return matched;
}

/** Short non-reversible key fingerprint for logs (never the key itself). */
export function keyFingerprint(candidate: string): string {
  return sha256(candidate).toString("hex").slice(0, 8);
}
